name: X86-OpenWrt

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      seed: X86
      artifact_prefix: X86-GC404
      sha_match: x86
      ext4_zip: "*ext4-combined*"
      sfs_zip: "*squashfs-combined*"
      sysupgrade_glob: "*combined-efi.img*"
      openwrt_source_name: openwrt-source-X86-${{ github.run_id }}.tar

    steps:
      - name: Show system info
        run: |
          echo -e "Total CPU cores\t: $(nproc)"
          cat /proc/cpuinfo | grep 'model name'

      - name: Maximize build space
        uses: smallprogram/maximize-build-space@master
        with:
          swap-size-mb: 1024
          temp-reserve-mb: 4608
          root-reserve-mb: 3584
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo /bin/bash -c "$(curl -sL https://git.io/vokNn)"
          sudo -E apt-fast -y -qq install asciidoc bash bcc bin86 binutils bison bzip2 clang file flex g++ g++-multilib gawk gcc-multilib gettext git gzip help2man intltool libbpf-dev libboost-dev libelf-dev libncurses-dev libssl-dev libthread-queue-any-perl libusb-dev libxml-parser-perl linux-tools-generic llvm make patch perl-modules pkg-config python3-dev python3-pip python3-pyelftools python3-setuptools rsync sharutils swig time unzip util-linux wget xsltproc zlib1g-dev zip zstd
          sudo -E apt-fast -y -qq install dos2unix dwarves jq npm quilt
          sudo -E npm install -g pnpm
          sudo -E npm install -g n
          sudo -E n stable
          pip3 install --user -U pylibfdt --break-system-packages
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo -E git config --global user.name 'GitHub Actions'
          sudo -E git config --global user.email 'noreply@github.com'
          sudo -E git config --global core.abbrev auto
          df -h

      - name: Prepare Mixedwrt
        run: |
          sudo chown -R runner:runner /home/runner/work/YAOF
          cp -r ./SCRIPTS/X86/. ./SCRIPTS/
          cp -r ./SCRIPTS/. ./
          /bin/bash 01_get_ready.sh

      - name: Prepare Package
        working-directory: ${{ github.workspace }}/openwrt
        run: |
          cp -r ../SCRIPTS/. ./
          /bin/bash 02_prepare_package.sh
          /bin/bash 02_target_only.sh
          /bin/bash 04_remove_upx.sh

      - name: Apply X86 config
        working-directory: ${{ github.workspace }}/openwrt
        run: |
          cp -rf ../SEED/X86/config.seed .config

      - name: Convert Translation
        working-directory: ${{ github.workspace }}/openwrt
        run: |
          /bin/bash 03_convert_translation.sh

      - name: Add ACL
        working-directory: ${{ github.workspace }}/openwrt
        run: |
          /bin/bash 05_create_acl_for_luci.sh -a

      - name: Fix Permissions
        working-directory: ${{ github.workspace }}/openwrt
        run: |
          sudo -E chmod -R 755 ./08_fix_permissions.sh
          /bin/bash 08_fix_permissions.sh

      - name: Make Config
        working-directory: ${{ github.workspace }}/openwrt
        run: |
          make defconfig

      - name: Make Download
        working-directory: ${{ github.workspace }}/openwrt
        run: |
          make download -j50
          make -j$(($(nproc) + 1)) package/network/utils/nftables/refresh V=s

      - name: Compile OpenWrt
        id: compileopenwrt
        working-directory: ${{ github.workspace }}/openwrt
        continue-on-error: true
        run: |
          IGNORE_ERRORS=1 make -j$(($(nproc) + 1))

      - name: If Compile Error
        if: steps.compileopenwrt.outcome == 'failure'
        working-directory: ${{ github.workspace }}/openwrt
        run: |
          cat ./.config
          echo '================================================================'
          make -j1 V=s

      - name: Organize firmware files
        run: |
          latest_release="$(curl -s https://github.com/openwrt/openwrt/tags | grep -Eo "v[0-9\.]+\-*r*c*[0-9]*.tar.gz" | sed -n '/[2-9][5-9]/p' | sed -n 1p | sed 's/.tar.gz//g' | sed 's/v//g')"
          echo "latest_release=${latest_release}" >> $GITHUB_ENV

          rm -rf ./artifact/
          mkdir -p ./artifact/

          mv openwrt/bin/targets/x86/64/${{ env.sysupgrade_glob }} ./artifact/

          cd ./artifact/
          ls -Ahl

          gzip -d *.gz || true
          gzip --best *.img

          sha256sum openwrt*${{ env.sha_match }}* | tee ${{ env.artifact_prefix }}-$(date +%Y-%m-%d)-${latest_release}.sha256sum

          zip ${{ env.artifact_prefix }}-$(date +%Y-%m-%d)-${latest_release}-ext4.zip ${{ env.ext4_zip }} || true
          zip ${{ env.artifact_prefix }}-$(date +%Y-%m-%d)-${latest_release}-sfs.zip ${{ env.sfs_zip }} || true

          ls -Ahl

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: X86-OpenWrt-firmware
          path: artifact/*
          retention-days: 7

      - name: Print Disk Space After
        run: df -h
